Linux: Makefile/configure: split GDK_PATH setting into two, include and NVML path

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -39,9 +39,13 @@ have_buildtype=no
 buildtype=
 default_buildtype=release
 
-have_gdk=no
-gdk_path=
-gdk_check=include/nvidia/gdk/nvml.h
+have_gdk_include=no
+gdk_include_path=
+gdk_include_check=nvml.h
+
+have_gdk_nvml_lib=no
+gdk_nvml_lib_path=
+gdk_nvml_lib_check=libnvidia-ml.so
 
 have_cub=no
 cub_path=
@@ -78,7 +82,8 @@ default_openblas=""
 # NOTE: Will get compilation errors with cuda-6.0
 default_cudas="cuda-7.5 cuda-7.0 cuda-6.5"
 default_kaldis="kaldi-trunk kaldi-c024e8aa"
-default_gdks=". gdk/usr"
+default_gdk_includes="include/nvidia/gdk"
+default_gdk_nvml_libs="src/gdk/nvml/lib"
 default_cubs="cub-1.4.1"
 default_cudnns="cudnn-4.0"
 default_opencvs="opencv-3.1.0 opencv-3.0.0"
@@ -145,9 +150,14 @@ function find_kaldi ()
     find_dir "$default_kaldis" "$kaldi_check"
 }
 
-function find_gdk ()
+function find_gdk_include ()
 {
-    find_dir "$default_gdks" "$gdk_check"
+    find_dir "$default_gdk_includes" "$gdk_include_check"
+}
+
+function find_gdk_nvml_lib ()
+{
+    find_dir "$default_gdk_nvml_libs" "$gdk_nvml_lib_check"
 }
 
 function find_cub ()
@@ -183,7 +193,7 @@ function is_hardlinked ()
 
 function default_use_cuda ()
 {
-    if test x$(find_cuda) = x || test x$(find_gdk) = x
+    if test x$(find_cuda) = x || test x$(find_gdk_include) = x || test x$(find_gdk_nvml_lib) = x || test x$(find_cudnn) = x || test x$(find_cub) = x
     then
         echo no
     else
@@ -213,7 +223,8 @@ function show_help ()
     echo "  --cuda[=(yes|no)] use cuda GPU $(show_default $(default_use_cuda))"
     echo "  --with-cuda[=directory] $(show_default $(find_cuda))"
     echo "  --with-cub[=directory] $(show_default $(find_cub))"
-    echo "  --with-gdk[=directory] $(show_default $(find_gdk))"
+    echo "  --with-gdk-include[=directory] $(show_default $(find_gdk_include))"
+    echo "  --with-gdk-nvml-lib[=directory] $(show_default $(find_gdk_nvml_lib))"
     echo "  --with-cudnn[=directory] $(show_default $(find_cudnn))"
     echo "  --with-acml[=directory] $(show_default $(find_acml))"
     echo "  --with-mkl[=directory] $(show_default $(find_mkl))"
@@ -336,23 +347,44 @@ do
                 fi
             fi
             ;;
-        --with-gdk*)
-            have_gdk=yes
+        --with-gdk-include*)
+            have_gdk_include=yes
             if test x$optarg = x
             then
-                gdk_path=$(find_gdk)
-                if test x$gdk_path = x
+                gdk_include_path=$(find_gdk_include)
+                if test x$gdk_include_path = x
                 then
-                    echo "Cannot find gdk directory."
-                    echo "Please specify a value for --with-gdk"
+                    echo "Cannot find GDK include directory."
+                    echo "Please specify a value for --with-gdk-include"
                     exit 1
                 fi
             else
-                if test $(check_dir $optarg $gdk_check) = yes
+                if test $(check_dir $optarg $gdk_include_check) = yes
                 then
-                    gdk_path=$optarg
+                    gdk_include_path=$optarg
                 else
-                    echo "Invalid gdk directory $optarg"
+                    echo "Invalid GDK include directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
+        --with-gdk-nvml-lib*)
+            have_gdk_nvml_lib=yes
+            if test x$optarg = x
+            then
+                gdk_nvml_lib_path=$(find_gdk_nvml_lib)
+                if test x$gdk_nvml_lib_path = x
+                then
+                    echo "Cannot find GDK NVML library directory."
+                    echo "Please specify a value for --with-gdk-nvml-lib"
+                    exit 1
+                fi
+            else
+                if test $(check_dir $optarg $gdk_nvml_lib_check) = yes
+                then
+                    gdk_nvml_lib_path=$optarg
+                else
+                    echo "Invalid GDK NVML library directory $optarg"
                     exit 1
                 fi
             fi
@@ -572,15 +604,27 @@ then
     fi
 fi
 
-if test $enable_cuda = yes && test x$gdk_path = x
+if test $enable_cuda = yes && test x$gdk_include_path = x
 then
-    gdk_path=$(find_gdk)
-    if test x$gdk_path = x ; then
-        echo Cannot locate a gdk directory
+    gdk_include_path=$(find_gdk_include)
+    if test x$gdk_include_path = x ; then
+        echo Cannot locate a GDK include directory
         echo GPU will be disabled
         enable_cuda=no
     else
-        echo Found gdk at $gdk_path
+        echo Found GDK include at $gdk_include_path
+    fi
+fi
+
+if test $enable_cuda = yes && test x$gdk_nvml_lib_path = x
+then
+    gdk_nvml_lib_path=$(find_gdk_nvml_lib)
+    if test x$gdk_nvml_lib_path = x ; then
+        echo Cannot locate a GDK NVML library directory
+        echo GPU will be disabled
+        enable_cuda=no
+    else
+        echo Found GDK NVML library at $gdk_nvml_lib_path
     fi
 fi
 
@@ -661,7 +705,8 @@ case $mathlib in
 esac
 if test $enable_cuda = yes ; then
     echo CUDA_PATH=$cuda_path >> $config
-    echo GDK_PATH=$gdk_path >> $config
+    echo GDK_INCLUDE_PATH=$gdk_include_path >> $config
+    echo GDK_NVML_LIB_PATH=$gdk_nvml_lib_path >> $config
     echo CUB_PATH=$cub_path >> $config
     echo CUDNN_PATH=$cudnn_path >> $config
 fi
